gg:
  jte:
    development-mode: true
    template-location: src/main/jte

server:
  port: 80
  servlet:
    session:
      cookie:
        same-site: strict
        secure: true

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources,src/main/jte
    livereload:
      enabled: true

  application:
    name: StudiesWebServer


token: "token123"
