gg:
  jte:
    developmentMode: true
    templateLocation: src/main/jte
    usePrecompiledTemplates: false

server:
  address: 127.0.0.1
  port: 80
  tomcat:
    max-swallow-size: 5GB
    max-http-form-post-size: 5GB

  servlet:
    session:
      cookie:
        same-site: strict
        secure: true

spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources,src/main/jte
    livereload:
      enabled: false

  session:
    store-type: 'redis'

  redis:
    host: 127.0.0.1
    port: 6379
    password: ''

  application:
    name: StudiesWebServer

study_upload_path: "study_uploads/"
song_upload_path: "song_uploads/"
sermon_upload_path: "sermon_uploads/"
