gg:
  jte:
    developmentMode: true
    templateLocation: src/main/jte
    usePrecompiledTemplates: false

server:
  port: 80
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

  servlet:
    session:
      cookie:
        same-site: strict
        secure: true

spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources,src/main/jte
    livereload:
      enabled: false

  application:
    name: StudiesWebServer

study_upload_path: "study_uploads/"
study_items_per_page: 10

song_upload_path: "song_uploads/"
song_items_per_page: 10

sermon_upload_path: "sermon_uploads/"
sermon_items_per_page: 10

