<header>
    @template.layouts._header(title = "Home")
</header>
<body>
@template.layouts._navbar()

<!-- Hero Section -->
<div class="py-5 mb-5">
    <div class="container">
        <div class="row align-items-center min-vh-50">
            <div class="col-lg-8 mx-auto text-center">
                <h1 class="display-2 fw-bold mb-4">
                    Welcome
                </h1>
            </div>
        </div>
    </div>
</div>

@template.layouts._footer()

</body>