name: Java CI with Gradle.

on:
  workflow_dispatch

jobs:
  build:
    permissions:
      contents: read
      security-events: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build with Gradle
        run: |
          chmod +x *
          ./gradlew clean build shadowJar

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: Website
          path: build/libs/*.jar